# LegalOps Specifications Configuration
# This file defines the structure and validation rules for all specifications

specifications:
  # API Specifications
  api:
    format: openapi
    version: "3.0.3"
    files:
      - path: "api/legalops-api.yaml"
        name: "LegalOps API"
        description: "Main API specification for LegalOps system"
        validation:
          strict: true
          warnings: true
        endpoints:
          - "/health"
          - "/auth/login"
          - "/clients"
          - "/matters"
          - "/documents"
          - "/time-entries"
          - "/users"

  # System Specifications
  system:
    format: markdown
    version: "1.0.0"
    files:
      - path: "system/architecture.md"
        name: "System Architecture"
        description: "Complete system architecture specification"
        sections:
          - "Overview"
          - "Architecture Principles"
          - "System Components"
          - "Data Flow"
          - "Security Architecture"
          - "Scalability Considerations"
          - "Monitoring and Logging"
          - "Deployment Architecture"
          - "Compliance Requirements"
          - "Technology Stack"
          - "Future Enhancements"

  # Compliance Specifications
  compliance:
    format: markdown
    version: "1.0.0"
    files:
      - path: "compliance/upl-compliance.md"
        name: "UPL Compliance"
        description: "Unauthorized Practice of Law compliance specification"
        sections:
          - "Overview"
          - "Legal Framework"
          - "Compliance Requirements"
          - "Implementation Requirements"
          - "Compliance Procedures"
          - "Risk Management"
          - "Implementation Checklist"

# Validation Rules
validation:
  # API Validation
  api:
    required_fields:
      - "openapi"
      - "info"
      - "paths"
      - "components"
    format_validation: true
    schema_validation: true
    example_validation: true

  # Markdown Validation
  markdown:
    required_sections:
      - "Overview"
      - "Requirements"
      - "Implementation"
    link_validation: true
    image_validation: true
    table_validation: true

# Documentation Generation
documentation:
  # Output directories
  output:
    api_docs: "docs/api"
    system_docs: "docs/system"
    compliance_docs: "docs/compliance"
  
  # Generation options
  options:
    include_examples: true
    include_schemas: true
    include_diagrams: true
    generate_pdf: false
    generate_html: true

# Integration Settings
integration:
  # GitHub Integration
  github:
    repository: "Andytreusch1028/LegalOps"
    branch: "main"
    auto_commit: false
    pull_request: true
  
  # CI/CD Integration
  ci_cd:
    validate_on_push: true
    generate_docs: true
    deploy_docs: false
  
  # External Tools
  tools:
    swagger_ui: true
    redoc: true
    postman: true
    insomnia: true

# Maintenance
maintenance:
  # Review Schedule
  review:
    frequency: "quarterly"
    responsible: "LegalOps Team"
    approval_required: true
  
  # Update Schedule
  updates:
    frequency: "monthly"
    auto_update: false
    notification: true
  
  # Archive Policy
  archive:
    keep_versions: 5
    archive_after: "1 year"
    delete_after: "3 years"
